# Project-wide Gradle settings

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ? AndroidX obligatoire
android.useAndroidX=true

# ? Supprime le warning compileSdk 35
android.suppressUnsupportedCompileSdk=35

# Kotlin
kotlin.code.style=official

# Performance Gradle
org.gradle.parallel=true
org.gradle.caching=true